### ISSUE TITLE
Empty macro crash

### ISSUE THREAD

**Issue by Erlandys** [VoxelPlugin/issues#25] opened 2023-05-24 13:40 UTC
**Describe the bug**
If you spawn macro node with macro which doesn't have any inputs or outputs, graph generation breaks down, throws quite few ensures and doesn't generate world at all.

**Affected release**
Is confirmed on last release and latest dev (`8156`)

**To Reproduce**
1. Create new macro;
2. Do not add any input/output parameters to it;
3. Drag it out to main graph.

**Expected behavior**
Spawning empty macro node should not affect graph execution, since you cannot connect it to anything, so it should do nothing.

**Observed behavior**
We get ensures and graph generation breaks:
```NewVoxelScene.Graph :  Generate Marching Cube Surface : Invalid chunk size```
```NewVoxelScene.Graph :  Generate Marching Cube Collider : Chunk Size should be between 8 and 128, is 0```
```Ensure condition failed: ChunkRef [File:D:\Unreal Projects\VoxelPluginPrivate 5.1\Plugins\VoxelPro\Source\VoxelGraphCore\Private\VoxelChunkSpawner.cpp] [Line: 27] ```

**Comment by JarrodSeymour** [comment] 2023-05-26 17:39
Reproduced on Dev debug 8180

Errors from log:

```
LogVoxel: Updating Graph.VoxelGraphStructNode_15.EnableNode: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.ChunkSpawner: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_10.ChunkScreenSize: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.VoxelSize: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.Distance: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.Material: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.BodyInstance: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.PhysicalMaterial: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.MeshSettings: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.TextureSizeBias: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.DistanceChecksTolerance: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_15.PerfectTransitions: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_1.EnableNode: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_1.Foliage_0: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.EnableNode: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.Scene: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.VoxelSize: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.ChunkSize: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.Distance: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.PhysicalMaterial: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_4.DistanceChecksTolerance: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_7.EnableNode: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_7.Name: compilation status changed
LogVoxel: Updating Graph.VoxelGraphStructNode_7.Value: compilation status changed
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph  failed to compile
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
LogStats: FPlatformStackWalk::StackWalkAndDump -  0.164 s
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: Bounds.Size() == FVector3d(ChunkSize * ScaledVoxelSize)  [File:C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphNodes\Private\MarchingCube\VoxelMarchingCubeNodes.cpp] [Line: 41] 
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ff8267e70fd UnrealEditor-VoxelGraphNodes.dll!<lambda_c83866a47644ffb02b4d6e147b74c6b0>::operator()() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphNodes\Private\MarchingCube\VoxelMarchingCubeNodes.cpp:49]
LogOutputDevice: Error: [Callstack] 0x00007ff8267986da UnrealEditor-VoxelGraphNodes.dll!VoxelCall<<lambda_8b135790970a277967143c24412ce62f>,FVoxelFutureValue>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelUniqueFunction.h:24]
LogOutputDevice: Error: [Callstack] 0x00007ff8273bd9f6 UnrealEditor-VoxelGraphCore.dll!<lambda_94cec9c55f9b352e093a2279897d4408>::operator()() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelTask.cpp:191]
LogOutputDevice: Error: [Callstack] 0x00007ff8273f68f6 UnrealEditor-VoxelGraphCore.dll!FVoxelTask::Execute() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelTask.cpp:137]
LogOutputDevice: Error: [Callstack] 0x00007ff82742eb58 UnrealEditor-VoxelGraphCore.dll!FVoxelTaskGroup::ProcessAsyncTasks() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelTaskGroup.cpp:321]
LogOutputDevice: Error: [Callstack] 0x00007ff82744cfb6 UnrealEditor-VoxelGraphCore.dll!FVoxelTaskExecutor::FThread::Run() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelTaskExecutor.cpp:421]
LogOutputDevice: Error: [Callstack] 0x00007ff850f722c2 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850f68310 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc387614 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc5226a1 ntdll.dll!UnknownFunction []
LogStats:                SubmitErrorReport -  0.000 s
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
LogStats:                    SendNewReport -  1.120 s
LogStats:             FDebug::EnsureFailed -  1.288 s
VoxelGraphErrors: Error: Generate Marching Cube Surface : Invalid chunk size
Voxel: Error: VS_Issue25.Graph :  Generate Marching Cube Surface : Invalid chunk size
LogStats: FPlatformStackWalk::StackWalkAndDump -  0.026 s
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: ChunkRef  [File:C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelChunkSpawner.cpp] [Line: 27] 
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ff8273eb0f6 UnrealEditor-VoxelGraphCore.dll!FVoxelChunkSpawnerImpl::CreateChunk() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelChunkSpawner.cpp:27]
LogOutputDevice: Error: [Callstack] 0x00007ff8267d54dc UnrealEditor-VoxelGraphNodes.dll!<lambda_69c39d9b58a995bd02376ee05ed789e8>::operator()() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphNodes\Private\VoxelScreenSizeChunkSpawner.cpp:174]
LogOutputDevice: Error: [Callstack] 0x00007ff82675d52a UnrealEditor-VoxelGraphNodes.dll!<lambda_0509458a874e3115d184dd05dd0648da>::operator()<>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelDelegateHelpers.h:229]
LogOutputDevice: Error: [Callstack] 0x00007ff850893a6f UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850879fbd UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850884b63 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508952d5 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508951bc UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850870045 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508c8172 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508837b0 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850a156d0 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850f722c2 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff850f68310 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc387614 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc5226a1 ntdll.dll!UnknownFunction []
LogStats:                SubmitErrorReport -  0.000 s
LogStats:                    SendNewReport -  2.541 s
LogStats:             FDebug::EnsureFailed -  2.577 s
LogOutputDevice: Warning: Script Stack (0 frames) :
LogStats: FPlatformStackWalk::StackWalkAndDump -  0.028 s
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: Node.IsValid()  [File:C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Public\VoxelNodeMessages.h] [Line: 33] 
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ff8272c93b1 UnrealEditor-VoxelGraphCore.dll!TVoxelMessageArgProcessor<FVoxelNodeRef,void>::ProcessArg() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Public\VoxelNodeMessages.h:33]
LogOutputDevice: Error: [Callstack] 0x00007ff826781f8a UnrealEditor-VoxelGraphNodes.dll!FVoxelMessages::LogMessage<FVoxelNodeRef const &>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelMessages.h:357]
LogOutputDevice: Error: [Callstack] 0x00007ff8267de7de UnrealEditor-VoxelGraphNodes.dll!<lambda_8e46f1fa6c078a7266a981e23a4fd813>::operator()() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphNodes\Private\VoxelScreenSizeChunkSpawner.cpp:244]
LogOutputDevice: Error: [Callstack] 0x00007ff82675da6a UnrealEditor-VoxelGraphNodes.dll!<lambda_eb22e03e15c1a1606f16b4151c36090c>::operator()<>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelDelegateHelpers.h:229]
LogOutputDevice: Error: [Callstack] 0x00007ff850893a6f UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508ad5c6 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508ad98d UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff836605fe4 UnrealEditor-Engine.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cbb77f UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd473c UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd482a UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd74f0 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cea4c4 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667ced996 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc387614 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc5226a1 ntdll.dll!UnknownFunction []
LogStats:                SubmitErrorReport -  0.000 s
LogStats:                    SendNewReport -  1.017 s
LogStats:             FDebug::EnsureFailed -  1.051 s
LogOutputDevice: Warning: Script Stack (0 frames) :
LogStats: FPlatformStackWalk::StackWalkAndDump -  0.019 s
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: Node  [File:C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelNodeMessages.cpp] [Line: 11] 
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ff82742d346 UnrealEditor-VoxelGraphCore.dll!TVoxelMessageArgProcessor<FVoxelNode,void>::ProcessArg() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphCore\Private\VoxelNodeMessages.cpp:11]
LogOutputDevice: Error: [Callstack] 0x00007ff826781f8a UnrealEditor-VoxelGraphNodes.dll!FVoxelMessages::LogMessage<FVoxelNodeRef const &>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelMessages.h:357]
LogOutputDevice: Error: [Callstack] 0x00007ff8267de7de UnrealEditor-VoxelGraphNodes.dll!<lambda_8e46f1fa6c078a7266a981e23a4fd813>::operator()() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelGraphNodes\Private\VoxelScreenSizeChunkSpawner.cpp:244]
LogOutputDevice: Error: [Callstack] 0x00007ff82675da6a UnrealEditor-VoxelGraphNodes.dll!<lambda_eb22e03e15c1a1606f16b4151c36090c>::operator()<>() [C:\ROOT\PackagedPlugin\HostProject\Plugins\Voxel\Source\VoxelCore\Public\VoxelMinimal\VoxelDelegateHelpers.h:229]
LogOutputDevice: Error: [Callstack] 0x00007ff850893a6f UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508ad5c6 UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8508ad98d UnrealEditor-Core.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff836605fe4 UnrealEditor-Engine.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cbb77f UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd473c UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd482a UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cd74f0 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667cea4c4 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff667ced996 UnrealEditor.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc387614 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff8bc5226a1 ntdll.dll!UnknownFunction []
LogStats:                SubmitErrorReport -  0.000 s
LogStats:                    SendNewReport -  2.692 s
LogStats:             FDebug::EnsureFailed -  2.724 s
Voxel: Error: Null: voxel.chunkspawner.MaxChunks reached
```

**Comment by Mr4Goosey** [comment] 2023-11-02 11:44
This has since been refactored. Closed as this issue is unlikely to still be relevant.

**Closed by Mr4Goosey** 2023-11-02 11:44 UTC
Labels: reproduced
